### PR TITLE
Interactive histogram for each census's DBH count

### PR DESCRIPTION
**Pull request by Starryz**

### CODE REVIEW

**Comment by rudeboybert** [comment]
Unfortunately b/c of an accidental commit to master, we're now in a "Merge conflict" situation. Watch this video on resolving [merge conflicts](https://www.loom.com/share/fa519cc05b6e49a8a86425b6adacfe68). If you have questions, book an appointment.

**Comment by Starryz** [comment]
Noted. Will fix ASAP!

**Comment by Starryz** [comment]
Hey @rudeboybert ! Sorry for the delay of response. Thanks for the video on merge conflict (super helpful and I never knew how to deal with that). Hopefully, this one works. In case I commit to master and do wrong again, I created a temporary branch for this. If we can merge, then we can get rid of it. Please let me know if there are any other issues!

**Comment by rudeboybert** [comment]
Whoops, I forgot that we're all working on the same forked repo. Thus after PR approval for anyone, I won't actually do the final merge but rather leave the fork as is.

**Pull request merged**
